name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'ui'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'maintenance'
      - 'quality'
      - 'configuration'
      - 'tooling'
      - 'testing'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
  default: patch
template: |
  ## O que há de novo?

  $CHANGES
